[book]
authors = ["Weinong Wang"]
language = "en"
multilingual = false
src = "src"
title = "Azure Kubelogin"
description = "A Kubernetes credential (exec) plugin implementing azure authentication"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/Azure/kubelogin"
