name: generate github pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/website.yaml"
      - "docs/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
          fetch-depth: 0

      - name: Set TOOLS_BIN_DIR and add to PATH
        run: |
          TOOLS_BIN_DIR="${HOME}/.cargo/bin"
          echo "TOOLS_BIN_DIR=${TOOLS_BIN_DIR}" >> ${GITHUB_ENV}
          echo "${TOOLS_BIN_DIR}" >> ${GITHUB_PATH}

      - name: Build
        run: make -C docs/book build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book/book
